# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
%define glib2_version           2.7.0
%define dbus_version            0.90
%define dbus_glib_version       0.70
%define polkit_version          0.92
# << macros

Name:       ConsoleKit
Summary:    System daemon for tracking users, sessions and seats
Version:    0.4.5
Release:    1
Group:      System/Libraries
License:    GPLv2+
URL:        http://www.freedesktop.org/wiki/Software/ConsoleKit
Source0:    http://www.freedesktop.org/software/ConsoleKit/dist/ConsoleKit-%{version}.tar.bz2
Source100:  ConsoleKit.yaml
Patch0:     consolekit-allow-with-parameters.patch
Patch1:     revert-upstream-commit-4f88-is-local.patch
Requires:   dbus >= %{dbus_version}
Requires:   dbus-glib >= %{dbus_glib_version}
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(dbus-1) >= %{dbus_version}
BuildRequires:  pkgconfig(dbus-glib-1) >= %{dbus_glib_version}
BuildRequires:  pkgconfig(glib-2.0) >= %{glib2_version}
BuildRequires:  pkgconfig(polkit-gobject-1) >= %{polkit_version}
BuildRequires:  pkgconfig(x11)
BuildRequires:  pam-devel
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  libtool


%description
ConsoleKit is a system daemon for tracking what users are logged
into the system and how they interact with the computer (e.g.
which keyboard and mouse they use).

It provides asynchronous notification via the system message bus.



%package libs
Summary:    ConsoleKit libraries
License:    MIT
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   pam
Requires:   dbus >= %{dbus_version}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
This package contains libraries and a PAM module for interacting
with ConsoleKit.


%package x11
Summary:    X11-requiring add-ons for ConsoleKit
License:    GPLv2+
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description x11
ConsoleKit contains some tools that require Xlib to be installed,
those are in this separate package so server systems need not install
X. Applications (such as xorg-x11-xinit) and login managers (such as
gdm) that need to register their X sessions with ConsoleKit needs to
have a Requires: for this package.


%package devel
Summary:    Development files for ConsoleKit
License:    MIT
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains headers and libraries needed for
developing software that is interacting with ConsoleKit.



%prep
%setup -q -n %{name}-%{version}

# consolekit-allow-with-parameters.patch
%patch0 -p1
# revert-upstream-commit-4f88-is-local.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --with-pid-file=%{_localstatedir}/run/console-kit-daemon.pid \
    --enable-pam-module \
    --with-pam-module-dir=/%{_lib}/security \
    --docdir=%{_datadir}/doc/%{name}-%{version} \
    --with-systemdsystemunitdir=/%{_lib}/systemd/system

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# make sure we don't package a history log
rm -f $RPM_BUILD_ROOT/%{_var}/log/ConsoleKit/history


# << install post



%post
# >> post
if [ -f /var/log/ConsoleKit/history ]; then
chmod a+r /var/log/ConsoleKit/history
fi
# << post




%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig







%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING
%config %{_sysconfdir}/dbus-1/system.d/ConsoleKit.conf
%{_datadir}/dbus-1/system-services/*.service
%{_datadir}/polkit-1/actions/*.policy
%dir %{_sysconfdir}/ConsoleKit
%dir %{_sysconfdir}/ConsoleKit/seats.d
%dir %{_sysconfdir}/ConsoleKit/run-seat.d
%dir %{_sysconfdir}/ConsoleKit/run-session.d
%dir %{_prefix}/lib/ConsoleKit
%dir %{_prefix}/lib/ConsoleKit/scripts
%dir %{_prefix}/lib/ConsoleKit/run-seat.d
%dir %{_prefix}/lib/ConsoleKit/run-session.d
%dir %{_var}/run/ConsoleKit
%attr(755,root,root) %dir %{_var}/log/ConsoleKit
%config %{_sysconfdir}/ConsoleKit/seats.d/00-primary.seat
%{_sbindir}/console-kit-daemon
%{_sbindir}/ck-log-system-restart
%{_sbindir}/ck-log-system-start
%{_sbindir}/ck-log-system-stop
%{_bindir}/ck-history
%{_bindir}/ck-launch-session
%{_bindir}/ck-list-sessions
%{_prefix}/lib/ConsoleKit/scripts/*

/%{_lib}/systemd/system/basic.target.wants/console-kit-log-system-start.service
/%{_lib}/systemd/system/console-kit-daemon.service
/%{_lib}/systemd/system/console-kit-log-system-restart.service
/%{_lib}/systemd/system/console-kit-log-system-start.service
/%{_lib}/systemd/system/console-kit-log-system-stop.service
/%{_lib}/systemd/system/halt.target.wants/console-kit-log-system-stop.service
/%{_lib}/systemd/system/poweroff.target.wants/console-kit-log-system-stop.service
/%{_lib}/systemd/system/reboot.target.wants/console-kit-log-system-restart.service
/%{_lib}/systemd/system/kexec.target.wants/console-kit-log-system-restart.service
# << files


%files libs
%defattr(-,root,root,-)
# >> files libs
%{_libdir}/lib*.so.*
/%{_lib}/security/*.so
%{_mandir}/man8/pam_ck_connector.8.gz
# << files libs

%files x11
%defattr(-,root,root,-)
# >> files x11
%{_libexecdir}/*
# << files x11

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/*
%{_includedir}/*
%{_datadir}/dbus-1/interfaces/org.freedesktop.ConsoleKit.*.xml
# << files devel

